/**
 * Single source of truth for every localStorage key this app uses.
 *
 * Before this file existed, each of these ~72 keys was a raw string
 * literal typed out separately everywhere it was read or written --
 * across 8+ files -- with no single place to see the full list or
 * catch a typo (a single mistyped character silently creates a second,
 * disconnected storage slot instead of erroring). Import STORAGE_KEYS
 * and reference a property instead of typing the string again.
 *
 * The property names are new; the string VALUES are unchanged from
 * before, so existing persisted data in a person's browser is read
 * exactly as before -- this is a pure refactor, not a data migration.
 */
export const STORAGE_KEYS = {
  settingsCollapsedSections: 'the_humidor_settings_collapsed_sections',
  cigarQuickQuoteRetailers: 'cigar_quick_quote_retailers',
  activeTab: 'the_humidor_active_tab',
  autoAddImportToResearch: 'the_humidor_auto_add_import_to_research',
  dashboardCustomizeOpen: 'the_humidor_dashboard_customize_open',
  dashboardSections: 'the_humidor_dashboard_sections',
  inventoryBrand: 'the_humidor_inventory_brand',
  inventoryDisplayFields: 'the_humidor_inventory_display_fields',
  inventoryOrigin: 'the_humidor_inventory_origin',
  inventoryPillCategory: 'the_humidor_inventory_pill_category',
  inventorySearch: 'the_humidor_inventory_search',
  inventorySelectedHumidor: 'the_humidor_inventory_selected_humidor',
  inventoryShowDisplayOptions: 'the_humidor_inventory_show_display_options',
  inventoryShowPills: 'the_humidor_inventory_show_pills',
  inventorySmokeTime: 'the_humidor_inventory_smoke_time',
  inventorySort: 'the_humidor_inventory_sort',
  inventoryStatus: 'the_humidor_inventory_status',
  inventoryStrength: 'the_humidor_inventory_strength',
  inventoryViewMode: 'the_humidor_inventory_view_mode',
  inventoryVitola: 'the_humidor_inventory_vitola',
  inventoryWrapper: 'the_humidor_inventory_wrapper',
  journalBrandFilter: 'the_humidor_journal_brand_filter',
  journalCutFilter: 'the_humidor_journal_cut_filter',
  journalDisplayFields: 'the_humidor_journal_display_fields',
  journalDurationFilter: 'the_humidor_journal_duration_filter',
  journalRatingFilter: 'the_humidor_journal_rating_filter',
  journalRebuyFilter: 'the_humidor_journal_rebuy_filter',
  journalSearch: 'the_humidor_journal_search',
  journalShowDisplayOptions: 'the_humidor_journal_show_display_options',
  journalSortBy: 'the_humidor_journal_sort_by',
  journalViewMode: 'the_humidor_journal_view_mode',
  journalVitolaFilter: 'the_humidor_journal_vitola_filter',
  journalWrapperFilter: 'the_humidor_journal_wrapper_filter',
  logSmokeSections: 'the_humidor_log_smoke_sections',
  researchActiveTab: 'the_humidor_research_active_tab',
  researchBrand: 'the_humidor_research_brand',
  researchOrigin: 'the_humidor_research_origin',
  researchPriceFilter: 'the_humidor_research_price_filter',
  researchQuickFilter: 'the_humidor_research_quick_filter',
  researchSearchTerm: 'the_humidor_research_search_term',
  researchShowDisplayOptions: 'the_humidor_research_show_display_options',
  researchShowFlavorProfile: 'the_humidor_research_show_flavor_profile',
  researchShowPairings: 'the_humidor_research_show_pairings',
  researchShowPersonalNotes: 'the_humidor_research_show_personal_notes',
  researchShowRetailerQuotes: 'the_humidor_research_show_retailer_quotes',
  researchShowReviews: 'the_humidor_research_show_reviews',
  researchSmokeTime: 'the_humidor_research_smoke_time',
  researchSortBy: 'the_humidor_research_sort_by',
  researchStrength: 'the_humidor_research_strength',
  researchViewMode: 'the_humidor_research_view_mode',
  researchVitola: 'the_humidor_research_vitola',
  researchWrapper: 'the_humidor_research_wrapper',
  sommelierDrink: 'the_humidor_sommelier_drink',
  sommelierMood: 'the_humidor_sommelier_mood',
  sommelierNotes: 'the_humidor_sommelier_notes',
  sommelierTime: 'the_humidor_sommelier_time',
  wishlistBasket: 'the_humidor_wishlist_basket',
  wishlistBrandFilter: 'the_humidor_wishlist_brand_filter',
  wishlistDisplayFields: 'the_humidor_wishlist_display_fields',
  wishlistPriorityFilter: 'the_humidor_wishlist_priority_filter',
  wishlistSearch: 'the_humidor_wishlist_search',
  wishlistShopBestOnly: 'the_humidor_wishlist_shop_best_only',
  wishlistShopFilter: 'the_humidor_wishlist_shop_filter',
  wishlistShowDisplayOptions: 'the_humidor_wishlist_show_display_options',
  wishlistSmokeTimeFilter: 'the_humidor_wishlist_smoke_time_filter',
  wishlistSort: 'the_humidor_wishlist_sort',
  wishlistViewMode: 'the_humidor_wishlist_view_mode',
  cedarAshCigars: 'cedar_ash_cigars',
  cedarAshHumidors: 'cedar_ash_humidors',
  cedarAshResearchDb: 'cedar_ash_research_db',
  cedarAshSettings: 'cedar_ash_settings',
  cedarAshSmokelogs: 'cedar_ash_smokelogs',
  cedarAshWishlist: 'cedar_ash_wishlist',
} as const;
